Repository dev-memento/ANDROID-MEMENTO, pull requests merged in 2025-01, with the labels that each got.

#2 Feat/#1 project setting
  .github/pull_request_template.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/memento/MainActivity.kt
  app/src/main/java/org/memento/Mememto.kt
  app/src/main/java/org/memento/core/Dummy.kt
  app/src/main/java/org/memento/core/util/UiState.kt
  app/src/main/java/org/memento/data/datastore/ReqresDataSource.kt
  app/src/main/java/org/memento/data/datastroeimpl/ReqresDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/Dummy.kt
  app/src/main/java/org/memento/data/dto/request/Dummy.kt
  app/src/main/java/org/memento/data/dto/response/ResponseReqresDto.kt
  app/src/main/java/org/memento/data/mapper/ResponseReqresMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/ReqresRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/ReqresService.kt
  app/src/main/java/org/memento/di/DataSourceModule.kt
  app/src/main/java/org/memento/di/NetWorkModule.kt
  app/src/main/java/org/memento/di/RepositoryModule.kt
  app/src/main/java/org/memento/di/ServiceModule.kt
  app/src/main/java/org/memento/domain/model/Reqres.kt
  app/src/main/java/org/memento/domain/repository/ReqresRepository.kt
  app/src/main/java/org/memento/presentation/StartDummyScreen.kt
  app/src/main/java/org/memento/presentation/main/MainActivity.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavGraph.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavigationType.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/component/BottomNavigationBar.kt
  app/src/main/java/org/memento/presentation/navigation/MainNavGraph.kt
  app/src/main/java/org/memento/presentation/navigation/Routes/Route.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresScreen.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresViewmodel.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/util/NoRippleClickable.kt
  app/src/main/res/drawable/add_white_24.xml
  app/src/main/res/drawable/ic_android_black_24.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐻효은🐻

#4 Feat/#3 color setting
  app/src/main/java/org/memento/MainActivity.kt
  app/src/main/java/org/memento/presentation/main/MainActivity.kt
  app/src/main/java/org/memento/ui/theme/Color.kt
  app/src/main/java/org/memento/ui/theme/Theme.kt
Labels: 🐶휘원🐶

#6 Feat/#5 typography setting
  app/src/main/java/org/memento/MainActivity.kt
  app/src/main/java/org/memento/presentation/main/MainActivity.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresScreen.kt
  app/src/main/java/org/memento/ui/theme/Theme.kt
  app/src/main/java/org/memento/ui/theme/Type.kt
  app/src/main/res/font/suite_bold.ttf
  app/src/main/res/font/suite_medium.ttf
  app/src/main/res/font/suite_regular.ttf
Labels: 🤢태정🤢

#9 [Add/#8] Gradient 색상 3종 추가
  app/src/main/java/org/memento/ui/theme/Color.kt
Labels: 🐶휘원🐶, ➕ [ADD]

#13 [Feat/#12] ci setting
  .editorconfig
  .github/workflows/memento_ci.yml
  app/build.gradle.kts
  app/src/androidTest/java/org/memento/ExampleInstrumentedTest.kt
  app/src/main/java/org/memento/core/Dummy.kt
  app/src/main/java/org/memento/core/util/UiState.kt
  app/src/main/java/org/memento/data/datastore/ReqresDataSource.kt
  app/src/main/java/org/memento/data/datastroeimpl/ReqresDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/Dummy.kt
  app/src/main/java/org/memento/data/dto/request/Dummy.kt
  app/src/main/java/org/memento/data/mapper/ResponseReqresMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/ReqresRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/ReqresService.kt
  app/src/main/java/org/memento/di/NetworkModule.kt
  app/src/main/java/org/memento/di/ServiceModule.kt
  app/src/main/java/org/memento/domain/model/Reqres.kt
  app/src/main/java/org/memento/presentation/StartDummyScreen.kt
  app/src/main/java/org/memento/presentation/main/MainActivity.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavGraph.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavigationType.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/component/BottomNavigationBar.kt
  app/src/main/java/org/memento/presentation/navigation/MainNavGraph.kt
  app/src/main/java/org/memento/presentation/navigation/Routes/Route.kt
  app/src/main/java/org/memento/presentation/navigation/routes/Route.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresScreen.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresViewModel.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresViewmodel.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/ui/theme/Color.kt
  app/src/main/java/org/memento/ui/theme/Theme.kt
  app/src/main/java/org/memento/ui/theme/Type.kt
  app/src/test/java/org/memento/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐻효은🐻, ⭐ [FEAT]

#18 [Fix/#7] fix project setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/memento/presentation/MainActivity.kt
  app/src/main/java/org/memento/presentation/StartDummyScreen.kt
  app/src/main/java/org/memento/presentation/main/MainActivity.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavGraph.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/BottomNavigationType.kt
  app/src/main/java/org/memento/presentation/main/bottomnavigation/component/BottomNavigationBar.kt
  app/src/main/java/org/memento/presentation/navigation/MainNavGraph.kt
  app/src/main/java/org/memento/presentation/navigation/routes/Route.kt
  app/src/main/java/org/memento/presentation/navigator/MainNavigator.kt
  app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationType.kt
  app/src/main/java/org/memento/presentation/navigator/component/MainNavHost.kt
  app/src/main/java/org/memento/presentation/navigator/route/MainNavigationBarRoute.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen1.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen2.kt
  app/src/main/java/org/memento/presentation/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/navigation/BottomSheetNavigation.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresScreen.kt
  app/src/main/java/org/memento/presentation/reqres/navigation/ReqresNavigation.kt
  app/src/main/java/org/memento/presentation/today/navigation/TodayNavigation.kt
  app/src/main/java/org/memento/presentation/todo/navigation/TodoNavigation.kt
Labels: 🔧 [FIX]

#20 Feat/#15 selector components
  app/src/main/java/org/memento/domain/type/SelectorType.kt
  app/src/main/java/org/memento/presentation/MementoChipSelector.kt
  app/src/main/java/org/memento/presentation/MementoTodoCheckBox.kt
  app/src/main/res/drawable/ic_deadline.xml
  app/src/main/res/drawable/ic_tag.xml
  app/src/main/res/values/strings.xml
  gradlew
Labels: 🐶휘원🐶, ⭐ [FEAT]

#24 [Hotfix/#22] 폴더링 구조 변경
  app/src/main/java/org/memento/presentation/component/MementoBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoChipSelector.kt
  app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTextBottomSheetItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTimePicker.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoCheckBox.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/type/ColorTagData.kt
  app/src/main/java/org/memento/presentation/type/DeadLineType.kt
  app/src/main/java/org/memento/presentation/type/RepeatType.kt
  app/src/main/java/org/memento/presentation/type/SelectorType.kt
Labels: 🐻효은🐻, 😮 [HOTFIX]

#25 [Feat/#16] common component
  app/build.gradle.kts
  app/src/main/java/org/memento/presentation/component/MememtoTopBar.kt
  app/src/main/java/org/memento/presentation/component/MementoAiFloatingButton.kt
  app/src/main/java/org/memento/presentation/component/MementoPriorityTile.kt
  app/src/main/java/org/memento/presentation/component/MementoUrgentChip.kt
  app/src/main/java/org/memento/presentation/component/MementoWeeklyCalendar.kt
  app/src/main/java/org/memento/presentation/type/PriorityTagType.kt
  app/src/main/java/org/memento/ui/theme/Color.kt
  app/src/main/java/org/memento/ui/theme/Type.kt
  app/src/main/res/drawable/ic_settings_26.xml
  app/src/main/res/drawable/ic_sparkle_29.xml
  app/src/main/res/font/suite_extrabold.ttf
  app/src/main/res/values/strings.xml
Labels: 🐻효은🐻, ⭐ [FEAT]

#28 [Feat/#23] onboarding UI
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/memento/presentation/MainActivity.kt
  app/src/main/java/org/memento/presentation/component/MementoChipSelector.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/navigator/MainNavigator.kt
  app/src/main/java/org/memento/presentation/navigator/component/MainNavHost.kt
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen1.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen2.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen3.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen4.kt
  app/src/main/java/org/memento/presentation/onboarding/SplashScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/component/OnboardingNextButton.kt
  app/src/main/java/org/memento/presentation/onboarding/component/OnboardingProgressBar.kt
  app/src/main/java/org/memento/presentation/onboarding/component/OnboardingQuestionBox.kt
  app/src/main/java/org/memento/presentation/onboarding/component/OnboardingTopAppBar.kt
  app/src/main/java/org/memento/presentation/onboarding/component/OnboardingYesNoButton.kt
  app/src/main/java/org/memento/presentation/onboarding/component/RoundCheckbox.kt
  app/src/main/java/org/memento/presentation/onboarding/component/RoundCheckboxWithText.kt
  app/src/main/java/org/memento/presentation/onboarding/component/RoundCheckboxWithTextField.kt
  app/src/main/java/org/memento/presentation/onboarding/component/SocialLoginButton.kt
  app/src/main/java/org/memento/presentation/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/memento/presentation/type/JobSelectionType.kt
  app/src/main/java/org/memento/presentation/type/OnboardingTopType.kt
  app/src/main/java/org/memento/presentation/type/YesNoButtonType.kt
  app/src/main/java/org/memento/ui/theme/Theme.kt
  app/src/main/res/drawable/btn_back.xml
  app/src/main/res/drawable/ic__winddown.xml
  app/src/main/res/drawable/ic_wakeup.xml
  app/src/main/res/drawable/img_calendar.xml
  app/src/main/res/drawable/img_google.png
  app/src/main/res/drawable/logo_memento_green.xml
  app/src/main/res/drawable/logo_memento_white.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 🐶휘원🐶, ⭐ [FEAT]

#29 [Feat/#27] todo UI
  app/src/main/java/org/memento/presentation/component/MementoWeeklyCalendar.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/todo/component/TodoBoxDown.kt
  app/src/main/java/org/memento/presentation/todo/component/TodoBoxUp.kt
  app/src/main/java/org/memento/presentation/todo/component/TodoDateLine.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🐶휘원🐶, ⭐ [FEAT]

#37 [Feat/#36] web view
  app/build.gradle.kts
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/MementoWebView.kt
  gradle/libs.versions.toml
Labels: 🐶휘원🐶, ⭐ [FEAT]

#31 [Feat/#26] today UI
  app/build.gradle.kts
  app/src/main/java/org/memento/data/mapper/ResponseReqresMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/ReqresRepositoryImpl.kt
  app/src/main/java/org/memento/domain/entity/AllDay.kt
  app/src/main/java/org/memento/domain/entity/Reqres.kt
  app/src/main/java/org/memento/domain/repository/ReqresRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoAiFloatingButton.kt
  app/src/main/java/org/memento/presentation/component/MementoPriorityTile.kt
  app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/component/MementoWeeklyCalendar.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresScreen.kt
  app/src/main/java/org/memento/presentation/reqres/ReqresViewModel.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/component/AllDayISecheduleTag.kt
  app/src/main/java/org/memento/presentation/today/navigation/TodayNavigation.kt
  app/src/main/res/drawable/ic_deadline.xml
  app/src/main/res/drawable/ic_event.xml
  app/src/main/res/drawable/ic_notion.png
  app/src/main/res/drawable/ic_progress.xml
  gradle/libs.versions.toml
Labels: 🐻효은🐻, ⭐ [FEAT]

#38 [Feat/#35] feat memento dialog
  app/src/main/java/org/memento/presentation/component/MementoDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoCheckBox.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/type/BottomSheetType.kt
  app/src/main/java/org/memento/presentation/type/DialogType.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_event.xml
Labels: 🤢태정🤢, ⭐ [FEAT]

#39 [Feat/#30] google login
  app/build.gradle.kts
  app/src/main/java/org/memento/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/org/memento/di/AuthModule.kt
  app/src/main/java/org/memento/domain/repository/AuthRepository.kt
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/viewmodel/LoginViewModel.kt
  gradle/libs.versions.toml
Labels: 🐶휘원🐶, ⭐ [FEAT]

#40 [Feat/#33] edit delete view
  app/src/main/java/org/memento/presentation/component/MementoPriorityTile.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoEisenScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/EditTodoScreen.kt
  gradle/libs.versions.toml
Labels: 🐻효은🐻, ⭐ [FEAT]

#44 [Hotfix/#43] google login 오류 수정
  app/google-services.json
Labels: 🐶휘원🐶, 😮 [HOTFIX]

#45 [Feat/#41] alert dialog component
  app/src/main/java/org/memento/presentation/component/MementoAlertDialog.kt
  app/src/main/res/values/strings.xml
Labels: 🐶휘원🐶, ⭐ [FEAT]

#51 [Feat/#42] Refactor UI
  app/build.gradle.kts
  app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationBar.kt
  app/src/main/java/org/memento/presentation/navigator/component/BottomNavigationType.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/util/LineThrough.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_today.xml
  app/src/main/res/drawable/ic_todo.xml
Labels: 🐻효은🐻, ⭐ [FEAT]

#53 [Fix/#49] bottom sheet fix detail
  app/src/main/java/org/memento/domain/entity/AddTodo.kt
  app/src/main/java/org/memento/presentation/component/MementoTimePicker.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddPlanScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddPlanViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
Labels: 🤢태정🤢, 🔧 [FIX]

#58 [Fix/#47] 온보딩 UI 수정 및 투두 UI 수정
  app/build.gradle.kts
  app/src/main/java/org/memento/presentation/MainActivity.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen1.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen2.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen3.kt
  app/src/main/java/org/memento/presentation/onboarding/component/RoundCheckboxWithText.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/util/ChangeStringToTagType.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🐶휘원🐶, 🔧 [FIX]

#62 [Feat/#52] today api
  app/src/main/java/org/memento/data/datasource/ScheduleDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/ScheduleDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseScheduleDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseScheduleMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/ScheduleRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/ScheduleService.kt
  app/src/main/java/org/memento/di/DataSourceModule.kt
  app/src/main/java/org/memento/di/RepositoryModule.kt
  app/src/main/java/org/memento/di/ServiceModule.kt
  app/src/main/java/org/memento/domain/entity/ScheduleList.kt
  app/src/main/java/org/memento/domain/repository/ScheduleRepository.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
Labels: 🐻효은🐻, ⭐ [FEAT], 🌀서버통신

#63 [Feat/#54] add todo api
  app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/request/RequestAddTodoDto.kt
  app/src/main/java/org/memento/data/mapper/toData/RequestAddTodoMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/domain/entity/AddTodo.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🤢태정🤢, ⭐ [FEAT], 🌀서버통신

#65 [Feat/#64] brain dump feat animation
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpAITextField.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
Labels: 🤢태정🤢, ⭐ [FEAT]

#67 [Feat/#66] add plan 성공 시 화면 닫힘 및 데이터 초기화
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt
Labels: 🤢태정🤢, ⭐ [FEAT]

#75 [Feat/#73] token save 및 자동 로그인
  app/src/main/java/org/memento/data/local/TokenDataStore.kt
  app/src/main/java/org/memento/presentation/MainActivity.kt
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/navigation/OnboardingNavigation.kt
  app/src/main/java/org/memento/presentation/onboarding/viewmodel/LoginViewModel.kt
Labels: 🐶휘원🐶, ⭐ [FEAT]

#72 [Feat/#61] todo api
  app/src/main/java/org/memento/data/datasource/TodoDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseTodoDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseTodoMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/TodoRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/TodoService.kt
  app/src/main/java/org/memento/di/DataSourceModule.kt
  app/src/main/java/org/memento/di/RepositoryModule.kt
  app/src/main/java/org/memento/di/ServiceModule.kt
  app/src/main/java/org/memento/domain/entity/TodoList.kt
  app/src/main/java/org/memento/domain/repository/TodoRepository.kt
  app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt
Labels: 🐻효은🐻, ⭐ [FEAT], 🌀서버통신

#76 [Feat/#59] user info update api
  app/src/main/java/org/memento/data/datasource/UserInfoDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/UserDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/request/RequestUserInfoUpdateDto.kt
  app/src/main/java/org/memento/data/mapper/toData/RequestUserInfoMapper.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseLoginMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/LoginRepositoryImpl.kt
  app/src/main/java/org/memento/data/repositoryimpl/UserInfoUpdateRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/UserInfoUpdateService.kt
  app/src/main/java/org/memento/di/DataSourceModule.kt
  app/src/main/java/org/memento/di/RepositoryModule.kt
  app/src/main/java/org/memento/di/ServiceModule.kt
  app/src/main/java/org/memento/domain/entity/Login.kt
  app/src/main/java/org/memento/domain/entity/UserInfo.kt
  app/src/main/java/org/memento/domain/repository/LoginRepository.kt
  app/src/main/java/org/memento/domain/repository/UserInfoUpdateRepository.kt
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen1.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen2.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen3.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen4.kt
  app/src/main/java/org/memento/presentation/onboarding/component/RoundCheckboxWithText.kt
  app/src/main/java/org/memento/presentation/onboarding/viewmodel/LoginViewModel.kt
  app/src/main/java/org/memento/presentation/onboarding/viewmodel/OnboardingViewModel.kt
  app/src/main/java/org/memento/presentation/type/SetTimeType.kt
  app/src/main/java/org/memento/presentation/util/ChangeBooleanToYesNoType.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🐶휘원🐶, ⭐ [FEAT], 🌀서버통신

#78 [Feat/#70] schedule, todo navigation 및 schedule 상세, 삭제 api 구현
  app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
  app/src/main/java/org/memento/data/datasource/ScheduleDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
  app/src/main/java/org/memento/data/datasourceimpl/ScheduleDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseScheduleDetailDto.kt
  app/src/main/java/org/memento/data/dto/response/ResponseTodoDetailDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseScheduleDetailMapper.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseTodoDetailMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
  app/src/main/java/org/memento/data/repositoryimpl/ScheduleRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/data/service/ScheduleService.kt
  app/src/main/java/org/memento/domain/entity/ScheduleDetail.kt
  app/src/main/java/org/memento/domain/entity/TodoDetail.kt
  app/src/main/java/org/memento/domain/repository/AddPlanRepository.kt
  app/src/main/java/org/memento/domain/repository/ScheduleRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoAlertDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoEditScheduleBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoEditTodoBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
  app/src/main/java/org/memento/presentation/type/DialogData.kt
  app/src/main/java/org/memento/presentation/type/DialogType.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🤢태정🤢, ⭐ [FEAT], 🌀서버통신

#79 [Feat/#69] todo list
  app/src/main/java/org/memento/data/datasource/TodoDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseScheduleDto.kt
  app/src/main/java/org/memento/data/dto/response/ResponseTodoCompleteDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseScheduleMapper.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseTodoMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/TodoRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/TodoService.kt
  app/src/main/java/org/memento/domain/entity/ScheduleList.kt
  app/src/main/java/org/memento/domain/entity/TodoList.kt
  app/src/main/java/org/memento/domain/repository/TodoRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/main/MainScreen.kt
  app/src/main/java/org/memento/presentation/navigator/component/MainNavHost.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
  app/src/main/java/org/memento/presentation/today/navigation/TodayNavigation.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt
  app/src/main/java/org/memento/presentation/todo/navigation/TodoNavigation.kt
Labels: 🐻효은🐻, ⭐ [FEAT], 🌀서버통신

#83 [Feat/#74] braindump api
  app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/request/RequestBrainDumpDto.kt
  app/src/main/java/org/memento/data/mapper/toData/RequestAddPlanMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/domain/entity/BrainDump.kt
  app/src/main/java/org/memento/domain/repository/AddPlanRepository.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpViewModel.kt
Labels: 🐶휘원🐶, ⭐ [FEAT], 🌀서버통신

#84 [Feat/#77] tag api
  app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseTagDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseAddPlanMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/domain/entity/Tag.kt
  app/src/main/java/org/memento/domain/repository/AddPlanRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
Labels: 🐶휘원🐶, ⭐ [FEAT], 🌀서버통신

#85 [Feat/#81] navigation feat schedule edit
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/presentation/component/MementoDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoEditTodoBottomSheet.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/MainPlusBottomSheet.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🤢태정🤢, ⭐ [FEAT], 🌀서버통신

#89 [Feat/#82] all day api
  app/src/main/java/org/memento/data/datasource/AddPlanDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/AddPlanDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/response/ResponseAllDayDto.kt
  app/src/main/java/org/memento/data/dto/response/ResponseUpTimeDto.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseAllDayMapper.kt
  app/src/main/java/org/memento/data/mapper/toDomain/ResponseUpTimeMapper.kt
  app/src/main/java/org/memento/data/repositoryimpl/AddPlanRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/AddPlanService.kt
  app/src/main/java/org/memento/data/service/ScheduleService.kt
  app/src/main/java/org/memento/domain/entity/AllDay.kt
  app/src/main/java/org/memento/domain/entity/UpTime.kt
  app/src/main/java/org/memento/domain/repository/AddPlanRepository.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
Labels: 🐻효은🐻, ⭐ [FEAT], 🌀서버통신

#92 [Hotfix/#91] tag id pass
  app/src/main/java/org/memento/presentation/component/MementoBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoTagBottomSheetItem.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
Labels: 🐶휘원🐶, 😮 [HOTFIX], 🌀서버통신

#94 [Feat/#88] todo feat edit delete
  app/src/main/java/org/memento/data/datasource/TodoDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
  app/src/main/java/org/memento/data/dto/request/RequestAddScheduleDto.kt
  app/src/main/java/org/memento/data/dto/request/RequestAddTodoDto.kt
  app/src/main/java/org/memento/data/repositoryimpl/TodoRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/TodoService.kt
  app/src/main/java/org/memento/domain/entity/AddSchedule.kt
  app/src/main/java/org/memento/domain/entity/AddTodo.kt
  app/src/main/java/org/memento/domain/repository/TodoRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoEditScheduleBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoEditTodoBottomSheet.kt
  app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
  app/src/main/java/org/memento/presentation/component/MementoTodoItem.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🤢태정🤢, ⭐ [FEAT], 🌀서버통신

#98 [Hotfix/#97] toDo screen api fix
  app/src/main/java/org/memento/data/datasourceimpl/TodoDataSourceImpl.kt
  app/src/main/java/org/memento/data/service/TodoService.kt
  app/src/main/java/org/memento/presentation/todo/TodoViewModel.kt
Labels: 🤢태정🤢, 😮 [HOTFIX], 🌀서버통신

#95 [Fix/90] todo today 로직 수정
  app/src/main/java/org/memento/data/datasource/ScheduleDataSource.kt
  app/src/main/java/org/memento/data/datasourceimpl/ScheduleDataSourceImpl.kt
  app/src/main/java/org/memento/data/repositoryimpl/ScheduleRepositoryImpl.kt
  app/src/main/java/org/memento/data/service/ScheduleService.kt
  app/src/main/java/org/memento/data/service/TodoService.kt
  app/src/main/java/org/memento/domain/repository/ScheduleRepository.kt
  app/src/main/java/org/memento/presentation/component/MementoScheduleItem.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
Labels: 🐻효은🐻, 🔧 [FIX], 🌀서버통신

#102 [Hotfix/#99] add logic fix
  app/src/main/java/org/memento/presentation/component/MementoEditScheduleBottomSheet.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/util/FormatDate.kt
Labels: 🤢태정🤢, 😮 [HOTFIX], 🌀서버통신

#103 [Feat/#100] ai loading animation
  app/src/main/java/org/memento/presentation/component/MementoAnimatedGlowBorder.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
Labels: 🐶휘원🐶, ⭐ [FEAT], 🌀서버통신
