Repository dev-memento/ANDROID-MEMENTO, pull requests merged in 2025-03, with the labels that each got.

#115 [hotfix/#114] orderNum 타입 변경
  app/src/main/java/org/memento/data/dto/response/ResponsePriorityTodoDto.kt
  app/src/main/java/org/memento/data/dto/response/ResponseScheduleDto.kt
  app/src/main/java/org/memento/data/dto/response/ResponseTodoDto.kt
  app/src/main/java/org/memento/domain/entity/ScheduleList.kt
  app/src/main/java/org/memento/domain/entity/TodoList.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
Labels: 😮 [HOTFIX]

#109 [Refactor/#107] 1차 QA 반영
  app/src/main/java/org/memento/data/util/Interceptor.kt
  app/src/main/java/org/memento/presentation/component/MementoDialog.kt
  app/src/main/java/org/memento/presentation/component/MementoTimePicker.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddScheduleScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoTagScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/AddToDoViewModel.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpAITextField.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpScreen.kt
  app/src/main/java/org/memento/presentation/plusbottomsheet/BrainDumpViewModel.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
Labels: 🤢태정🤢, ♻️ [REFACTOR]

#116 [Refactor/#106] first qa
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayViewModel.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: 🐻효은🐻, ♻️ [REFACTOR]

#117 [Refactor/#105] onboarding UI
  app/src/main/java/org/memento/presentation/onboarding/LoginScreen.kt
  app/src/main/java/org/memento/presentation/onboarding/OnboardingScreen3.kt
  app/src/main/java/org/memento/presentation/onboarding/SplashScreen.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/res/drawable/logo_memento_white.xml
Labels: 🐶휘원🐶, ♻️ [REFACTOR]

#121 [Feat/#120] taejung setting component
  app/src/main/java/org/memento/presentation/setting/SettingScreen.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingAlertDialog.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingSocialChip.kt
  app/src/main/res/values/strings.xml
Labels: 🤢태정🤢, ⭐ [FEAT]

#127 [Feat/#124] hyoeun setting component
  app/src/main/java/org/memento/presentation/component/MememtoTopBar.kt
  app/src/main/java/org/memento/presentation/navigator/MainNavigator.kt
  app/src/main/java/org/memento/presentation/navigator/component/MainNavHost.kt
  app/src/main/java/org/memento/presentation/setting/SettingScreen.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingAddTag.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingTag.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingTopBar.kt
  app/src/main/java/org/memento/presentation/setting/component/TagColorSelector.kt
  app/src/main/java/org/memento/presentation/setting/component/TagNameTextField.kt
  app/src/main/java/org/memento/presentation/setting/navigation/SettingNavigation.kt
  app/src/main/java/org/memento/presentation/today/TodayScreen.kt
  app/src/main/java/org/memento/presentation/today/navigation/TodayNavigation.kt
  app/src/main/java/org/memento/presentation/todo/TodoScreen.kt
  app/src/main/java/org/memento/presentation/type/SettingTopBarType.kt
  app/src/main/res/drawable/ic_add_gray_26.xml
  app/src/main/res/drawable/ic_right_26.xml
  app/src/main/res/values/strings.xml
Labels: 🐻효은🐻, ⭐ [FEAT]

#133 [Feat/#132] setting integration 뷰 및 로직 작성
  app/src/main/java/org/memento/presentation/setting/SettingIntegrationsScreen.kt
  app/src/main/java/org/memento/presentation/setting/component/SettingAlertDialog.kt
  app/src/main/res/drawable/img_slack.png
  app/src/main/res/values/strings.xml
Labels: 🤢태정🤢, ⭐ [FEAT]
